import nextIcon from "../public/next.svg";

export const navItems = [
  { name: "About", link: "#about" },
  { name: "Projects", link: "#projects" },
  { name: "Experience", link: "#experience" },

  // { name: "Testimonials", link: "#testimonials" },
  { name: "Contact", link: "#contact" },
];

export const gridItems = [
  {
    id: 1,
    title:
      "I focus on building efficient, scalable applications with optimal user experiences. With a strong dedication to code quality and problem-solving, I strive to deliver innovative solutions in every project I undertake.",
    description: "",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full",
    titleClassName: "justify-end",
    img: "/b1.svg",
    spareImg: "",
  },
  {
    id: 2,
    title: "I'm very flexible with time zone communications",
    description: "",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "",
    spareImg: "",
  },
  {
    id: 3,
    title: "My tech stack",
    description: "",
    className: " md:col-span-3 md:row-span-1 order-2",
    imgClassName: "",
    titleClassName: "justify-start items-center lg:-mt-7",
    img: "",
    spareImg: "",
  },
  {
    id: 4,
    title: "Tech enthusiast with a passion for development.",
    description: "",
    className: "md:col-span-2 md:row-span-2 order-1",
    imgClassName: "",
    titleClassName: "justify-start",
    img: "/grid.svg",
    spareImg: "/b4.svg",
  },

  // {
  //   id: 5,
  //   title: "Currently building a JS Animation library",
  //   description: "The Inside Scoop",
  //   className: "md:col-span-3 md:row-span-2",
  //   imgClassName: "absolute right-0 bottom-0 md:w-96 w-60",
  //   titleClassName: "justify-center md:justify-start lg:justify-center",
  //   img: "/b5.svg",
  //   spareImg: "/grid.svg",
  // },
  {
    id: 6,
    title: "Do you want to start a project together?",
    description: "",
    className: "md:col-span-2 md:row-span-1 order-last",
    imgClassName: "",
    titleClassName: "justify-center md:max-w-full max-w-60 text-center",
    img: "",
    spareImg: "",
  },
];

export const projects = [
  {
    id: 1,
    title: "Rekreasi AI",
    des: "Itinerary generated by Artificial Intelligence, integrated with Chat GPT",
    img: "/projects/p1.png",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/next.svg", "/node.svg"],
    link: "https://rekreasi.com/",
  },
  {
    id: 2,
    title: "Member Harian Jogja",
    des: "A membership management application for news readers of Harian Jogja.",
    img: "/projects/p2.png",
    iconLists: ["/next.svg", "/tail.svg"],
    link: "https://member.harianjogja.com/",
  },
  {
    id: 3,
    title: "Vmaana",
    des: "An application that stores information about parks around the world.",
    img: "/projects/p3.png",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/next.svg", "/node.svg"],
    link: "https://vmaana.com/",
  },
  {
    id: 4,
    title: "Royalstar",
    des: "Project auction app (integrated with accurate)",
    img: "/projects/p4.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/nest.svg", "/node.svg"],
    link: "https://lelang.royalstar.id/",
  },
  {
    id: 5,
    title: "Genza Education",
    des: "Online tutorial Classes Landing Page with Dashboard Admin for change content",
    img: "/projects/p5.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/node.svg"],
    link: "https://web.genzaeducation.com/",
  },
  {
    id: 6,
    title: "Atomionics",
    des: "Company Profile with Dashboard Admin for change content",
    img: "/projects/p6.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/node.svg"],
    link: "https://www.atomionics.com/",
  },
  {
    id: 7,
    title: "Bobil",
    des: "Cars auction app",
    img: "/projects/p7.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/nest.svg", "/node.svg"],
    link: "https://bobil.monite.id/",
  },
  {
    id: 8,
    title: "Praxium",
    des: "Online Tutorial Classes",
    img: "/projects/p8.png",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/nest.svg", "/node.svg"],
    link: "https://praxium.monite.id",
  },
];

export const testimonials = [
  {
    quote:
      "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote:
      "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote:
      "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote:
      "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
  {
    quote:
      "Collaborating with Adrian was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Adrian's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Adrian is the ideal partner.",
    name: "Michael Johnson",
    title: "Director of AlphaStream Technologies",
  },
];

export const companies = [
  {
    id: 1,
    name: "cloudinary",
    img: "/cloud.svg",
    nameImg: "/cloudName.svg",
  },
  {
    id: 2,
    name: "appwrite",
    img: "/app.svg",
    nameImg: "/appName.svg",
  },
  {
    id: 3,
    name: "HOSTINGER",
    img: "/host.svg",
    nameImg: "/hostName.svg",
  },
  {
    id: 4,
    name: "stream",
    img: "/s.svg",
    nameImg: "/streamName.svg",
  },
  {
    id: 5,
    name: "docker.",
    img: "/dock.svg",
    nameImg: "/dockerName.svg",
  },
];

export const workExperience = [
  {
    id: 1,
    title: "Fullstack Developer",
    company: "Monite Id, Yogyakarta, Indonesia (Remote)",
    points: [
      "Developed user-friendly interfaces using HTML, CSS, JavaScript, and other front-end technologies for seamless user experience.",
      "Developed responsive web applications to provide consistent user experiences across multiple devices and platforms.",
      "Reviewed code, debugged problems, and corrected issues. Developed functional databases, applications and servers to support websites on back-end.",
      "Integrated third-party APIs to enhance functionality and improve overall user experience on web platforms.",
    ],
    className: "md:col-span-2",
    startDate: "2023 09",
    endDate: "2024 09",

    thumbnail: "/exp1.svg",
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "Semesta Group, Surakarta, Indonesia",
    points: [
      "Design, develop, and maintain scalable web applications across multiple platforms.",
      "Collaborate with cross-functional teams to define, design, and ship new features.",
      "Ensure the performance, quality, and responsiveness of applications. Identify and correct bottlenecks and fix bugs.",
      "Maintain code quality, organization, and automatization",
      "Engage in all phases of the software development lifecycle, including requirements gathering, design, coding, testing, and deployment.",
    ],
    className: "md:col-span-2", // change to md:col-span-2
    thumbnail: "/exp2.svg",
    startDate: "2023 05",
    endDate: "2023 08",
  },
  {
    id: 3,
    title: "Web Developer",
    company: "Tebar Digital, Surakarta, Indonesia",
    points: [
      "Developed user-friendly interfaces using HTML, CSS, JavaScript, and other front-end technologies for seamless user experience",
      "Design, develop, and maintain scalable web applications across multiple platforms",
      "Collaborate with cross-functional teams to define, design, and ship new features",
      "Ensure the performance, quality, and responsiveness of applications",
      "Identify and correct bottlenecks and fix bugs",
      "Maintain code quality, organization, and automatization",
    ],
    className: "md:col-span-2", // change to md:col-span-2
    thumbnail: "/exp3.svg",
    startDate: "2022 06",
    endDate: "2023 02",
  },
  {
    id: 4,
    title: "Frontend Developer",
    company: "Shotflow, Australia (Remote)",
    points: [
      "Developed user-friendly interfaces using HTML, CSS, JavaScript, and other front-end technologies for seamless user experience",
      "Design, develop, and maintain scalable web applications across multiple platforms",
      "Collaborate with cross-functional teams to define, design, and ship new features",
      "Ensure the performance, quality, and responsiveness of applications",
      "Identify and correct bottlenecks and fix bugs",
      "Maintain code quality, organization, and automatization",
    ],
    className: "md:col-span-2",
    thumbnail: "/exp4.svg",
    startDate: "2022 01",
    endDate: "2022 05",
  },
];

export const socialMedia = [
  {
    id: 1,
    img: "/git.svg",
    link: "https://github.com/abrar-byte",
  },
  {
    id: 2,
    img: "/upwork.svg",
    link: "https://www.upwork.com/freelancers/~01bb4591bfc627d0e3",
  },
  {
    id: 3,
    img: "/link.svg",
    link: "https://www.linkedin.com/in/usamah-hafidz-91a6ab225/",
  },
];

export const experiences = [
  {
    title: "React.js Developer",
    company_name: "Starbucks",
    icon: "/next.svg",
    iconBg: "#383E56",
    date: "March 2020 - April 2021",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "React Native Developer",
    company_name: "Tesla",
    // icon: tesla,
    icon: "/next.svg",

    iconBg: "#E6DEDD",
    date: "Jan 2021 - Feb 2022",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Web Developer",
    company_name: "Shopify",
    // icon: shopify,
    icon: "/next.svg",

    iconBg: "#383E56",
    date: "Jan 2022 - Jan 2023",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Full stack Developer",
    company_name: "Meta",
    // icon: meta,
    icon: "/next.svg",

    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];
